# permissions for end users to edit vehicles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: coden
    app.kubernetes.io/managed-by: kustomize
  name: vehicle-editor-role
rules:
- apiGroups:
  - iov.example.io.coden.io
  resources:
  - vehicles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iov.example.io.coden.io
  resources:
  - vehicles/status
  verbs:
  - get
